version: "3"
services:
  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - '2181:2181'
    restart: unless-stopped

  kafka:
    image: 'wurstmeister/kafka'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOSTNAME: /**host ip**/
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9095,OUTSIDE:// /**host ip**/ :9092
      KAFKA_LISTENERS: INSIDE://:9095,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - zookeeper
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: elasticsearch
    # 1 cluster
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02,es03
      # - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    # networks:
    #   - elastic   

  # Optional
  # Runs a GUI for kafka admin
  kafka-ui:
    image: provectuslabs/kafka-ui
    depends_on:
      - "kafka"
    container_name: kafka-ui
    ports:
      - "8090:8080"
    restart: unless-stopped
    environment:
     - KAFKA_CLUSTERS_0_NAME=local
     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9095
     - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
  
  # TODO:
  # Maybe add Kibana container if es-head chrome extension sucks

  # 1 volume for 1 cluster
volumes:
  esdata:
    driver: local

    
